name: Venni Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: venni_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm install
          npm run bootstrap
          npm run build
          npm test
        env:
          NODE_ENV: test
          TEST_DATABASE: venni_test
          TEST_DATABASE_USER: postgres
          TEST_DATABASE_PASSWORD: postgres
          TEST_DATABASE_HOST: localhost
          TEST_DATABASE_PORT: ${{ job.services.postgres.ports[5432] }}
          SALT_ROUNDS: 8
          SECRET_KEY: gasolineandsauce
          CI: true
